name: example
description: Single item storage example project.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  single_item_storage: ^2.0.0
  single_item_shared_prefs:
    path: ../single_item_shared_prefs
  single_item_secure_storage:
    path: ../single_item_secure_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true