name: single_item_storage
description: A single item storage abstraction with CRUD operations.
  Use it for abstracting (complex) storage implementations, testing,
  and quickly swapping implementations.
version: 2.0.1
homepage: https://github.com/dimitar-zabaznoski/single-item-storage-dart

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  async: any

dev_dependencies:
  test: any
  mockito: ^5.4.4
