name: single_item_shared_prefs
description: SharedPreferences/UserDefaults persistent Storage implementation.
version: 2.0.1
homepage: https://github.com/dimitar-zabaznoski/single-item-storage-dart

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  single_item_storage: ^2.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  mockito: ^5.4.4

