name: single_item_secure_storage
description: Keychain/Keystore persistent Storage implementation.
  Uses `flutter_secure_storage` under a `Storage` abstraction.
version: 2.1.0
homepage: https://github.com/dimitar-zabaznoski/single-item-storage-dart

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  single_item_storage: ^2.0.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  mockito: ^5.4.4